services:
  mariadb:
    image: mariadb:latest
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped

    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

    ports:
      - "${PORT}:3306"

    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10

  loader:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    environment:
      HOST: mariadb
      PORT: 3306
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data: